language: java

jdk:
  - oraclejdk8

install:
  - mvn --settings ../.travis/settings.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

before_install:
  - cd stl-decomp-4j
  - if [ ! -z "$GPG_SECRET_KEYS" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi
  - if [ ! -z "$GPG_OWNERTRUST" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi

deploy:
  -
    provider: script
    script: ../.travis/deploy.sh
    skip_cleanup: true
    on:
      repo: ServiceNow/stl-decomp-4j
      branch: master
      jdk: oraclejdk8
  -
    provider: script
    script: ../.travis/deploy.sh
    skip_cleanup: true
    on:
      repo: ServiceNow/stl-decomp-4j
      tags: true
      jdk: oraclejdk8
